### ISSUE TITLE
Servo module not loading(?)

### ISSUE THREAD

**Issue by scorpion451** [BobPalmer/Konstruction#15]
So I've got a mystery for you:
I have all the parts from this mod, the akita rover works and has its generator, the rest of the constellation works perfectly... just no servo-module-related controls or features.  None of the parts from this mod have any of their servo-related right-click menu options, and I don't have a servo app button on my toolbar.  

For a couple concrete examples, I have a space station with a bunch of construction docking ports. They work perfectly as docking ports that snap to a fixed angle... but there are no options to collapse them or adjustment sliders. Just a standard docking port right click menu. I can also launch an akita with a claw attached to it's flatbed. The akita works, the claw might as well be a bent girder. 

Been trying to figure it out for days, no dice. I've tried running it with all other mods but the USI constellation, and the latest versions of KAS and KIS pulled out, I've tried re-downloading and reinstalling several times, I've reloaded the database watching for glaring warnings... it just simply seems like MM has decided it doesn't want to load the servo module on my game no matter what I do.

I found at least one other person with the same problem, so I know I'm not completely crazy here: http://forum.kerbalspaceprogram.com/index.php?/topic/149365-konstruction-servo-control/

Hope that's enough info to at least let you know what you need me to look at for further bug-hunting.

**Edit:** Note to self making error report while tired: remembering to include the log file helps.
[KSP_log.txt](https://github.com/BobPalmer/Konstruction/files/531939/KSP_log.txt)
Looking at them, I begin to think there might be more that it's not loading... is there supposed to be a panel for planetary logistics? I've only ever seen the one for USI Life Support...

**Comment by scorpion451** [comment]
Maybe sort of fix it (still poking at things) - not sure exactly why it's working now, but after I deleted  usi_tools, and everything in the mks and konstruction zips, and reinstalled each fresh from the latest builds of mks and konstruction (in that order) I now seem to have functioning mods.

**Comment by dboi88** [comment]
Suggest close. Issue was resolved and not been reported since.
