### ISSUE TITLE
Increasing port range and force causes phantom forces on ship

### ISSUE THREAD

**Issue by stub42** [BobPalmer/Konstruction#24]
Put a Konstruction collapsible docking port on a vessel and jack its force and range up to maximum. Watch as its orbit changes and it probably starts to spin. I'm unsure if the docking port is doing it all by itself, or if it is interacting with other collapsible docking ports on the same vessel. While perpetual motion is cool, it kind of makes it hard to actually dock.

**Comment by dboi88** [comment]
I've done quite a lot of playing around with some worse case scenario crafts (multi docking ports close together, docking ports pointing at each other ect.) and have been unable to create any phantom forces. Suggest close issue.
