### ISSUE TITLE
Construction Ports not docking

### ISSUE THREAD

**Issue by nevercast** [BobPalmer/Konstruction#25]
Konstruction  0.1.6.0
KSP 1.2.0.1586 (x64, Windows)

Hello,

Using the latest release of Konstruction at the time, I am unable to dock two construction ports. I've played with all the adjustables, turning snap on and off, changing the force or port range. None of which allow me to dock, at first I thought I was being a bad pilot but MechJeb is unable to dock either. 

The console is filled with the following exception

```
[EXC 15:37:39.202] NullReferenceException: Object reference not set to an instance of an object
    ModuleDockingNode.<SetupFSM>m__2C6 (.KFSMState st)
    KerbalFSM.updateFSM (KFSMUpdateMode mode)
    KerbalFSM.UpdateFSM ()
    ModuleDockingNode.Update ()
```

![20161025153203_1](https://cloud.githubusercontent.com/assets/834342/19671114/dd92d21c-9ac8-11e6-896b-23fa66060154.jpg)

**Comment by nevercast** [comment]
After restarting the game it was still broken, however after doing a quick save and reload, it docked. I wont close the issue in case it's still a point of investigation.

**Comment by SCESW** [comment]
I spent a couple of hours trying to get parts docked to my new station in career mode.  Quick saving, loading... quitting the game, reloading.  Looked through .cfg files and finally turned off the "snap" option on the port that I was controlling and "Bam!" it worked.
So, my finding is that both ports can not have 'Snap' turned on.  Turn it off of one of the ports.  Perhaps there could be a check associated with this in the code that turns off one if 2 bump into one another?  I'm not a coder, just throwing out ideas.

**Comment by Ranger677** [comment]
I was able to get them to work by rotating the part being docked.  Once that did not work but I backed off and tried again and then it worked, again after rotating

**Comment by rspeed** [comment]
Isn't the purpose of the snap feature to prevent ports from connecting until they're properly aligned?

**Comment by dboi88** [comment]
Just closing this issue. The only known, current or reproducible bug is the root part issue.
