### ISSUE TITLE
Problem with collider on forklift?

### ISSUE THREAD

**Issue by spikethedoggy** [BobPalmer/Konstruction#31]
Hi Rover Dude. Whilst testing out the forklift I noticed that when trying to pick up a cradle, the left fork on the forklift was going straight through the cradle. The right one was fine. Tested again on a clean install with only USI mods and all up to date according to your catalogue page and AVC.
![screenshot4](https://cloud.githubusercontent.com/assets/24255301/20723671/59212b80-b663-11e6-97ab-630bbee8b35b.png)
Not sure how to upload a log file or exactly which one you'd need but give me a shout if you need one and I'll try and work it out.
Regards
Jon

**Comment by rspeed** [comment]
Can you rule out that it isn't a problem with the cradle? For example, have you tried picking up a different object?

**Comment by spikethedoggy** [comment]
Yes i have and the problem is with the left fork of the forklift and not the cradle. As you can see from the image the right fork has the collider and the left doesn't. Opened the issue on 29th Nov and no response so probably won't bother again.

**Comment by rspeed** [comment]
Picking up an object requires that their collider meshes come into contact. The behavior you're seeing could also be caused by an issue with the collider mesh on the cradle.

**Comment by BobPalmer** [comment]
Updated colliders in next patch, let me know if it sorts this
