### ISSUE TITLE
Mod does not work

### ISSUE THREAD

**Issue by pyalot** [BobPalmer/Konstruction#4]
When putting the mod files in the GameData folder (no module manager, no other mods there), none of the parts are available and the debug log shows the following when starting to load the mod:

![image](https://cloud.githubusercontent.com/assets/592826/19079422/e1ea67d8-8a53-11e6-8feb-8a88622e6552.png)

![image](https://cloud.githubusercontent.com/assets/592826/19079439/eb6f0836-8a53-11e6-8d48-2139ececa905.png)

![image](https://cloud.githubusercontent.com/assets/592826/19079450/f20f25e0-8a53-11e6-9f6b-e89fe75cec14.png)

This happens for the release downloaded from spacedock for Kerbal 1.1.3, as well as the releases from the github releases pages (for whatever kerbal they are, presumably 1.1.3), and the version of Kerbal tested with is 1.1.3.

**Comment by Zuke97** [comment]
He specifically says it will not work for 1.1.3 it is a 1.2 pre release only mod. http://forum.kerbalspaceprogram.com/index.php?/topic/149233-12-pre-konstruction-weldable-ports-servos-cranes-and-magnets/&page=1
spacedock says 1.1.3 since they do not provide the option to set it to any higher version

**Comment by pyalot** [comment]
I've seen some mods include a config file designating compatible versions and other data. I believe that would be the ckan metadata file https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md

**Comment by BobPalmer** [comment]
It will not work in 1.1.3.  If it was just a switch in a text file, you would not be getting that log spam ;)
