### ISSUE TITLE
Akita core/seat not a command seat

### ISSUE THREAD

**Issue by OfficiallyBrown** [BobPalmer/Konstruction#63]
I'm using KSP 1.2.2 with Konstruction 1.12.0. When I place the Core or command seat on a crane it tells me there is no way to control the craft

**Comment by BobPalmer** [comment]
Sure, because those are command seats... which require a Kerbal.

**Comment by OfficiallyBrown** [comment]
How exactly am I supposed toput a kerbal in it if it wont let me?
I understand you have to put the seat on the core, but going into the crew tab, the seat isnt listed as a part with a crew capacity

**Comment by BobPalmer** [comment]
Exactly the same way you would put a Kerbal in any command seat.  Suggest hitting the KSP forums or google for details.
