### ISSUE TITLE
[1.11.1] Cannot interact with mod parts in EVA construction mode

### ISSUE THREAD

**Issue by thiagoloddi** [BobPalmer/Konstruction#81]
Tried to move/replace some docking ports in a station but I can't interact with Konstruction parts. In the screenshot you can see parts that can be moved are highlighted green, but the docking port is not.
![20210220171313_1](https://user-images.githubusercontent.com/10400276/108607678-85b31600-73a0-11eb-9668-af8607e8aac0.jpg)

**Comment by tjdeckard** [comment]
Thanks for letting us know. We plan to deprecate the construction ports in a future release and just add the functionality they provide to the stock docking ports via Module Manager config. So that will be the "fix" for this issue.
