### ISSUE TITLE
The konfabricator button in the KS-250 does nothing

### ISSUE THREAD

**Issue by Tacombel** [BobPalmer/Konstruction#86]
![image](https://user-images.githubusercontent.com/17971083/111796369-6688a500-88c8-11eb-94c1-13857053ae30.png)

**Comment by geostar1024** [comment]
Just to check, have you tried launching it and activating it in orbit? For me, it wouldn't work on the launch pad (even with an engineer and the requisite Materialkits), but it does seem to function once in orbit.

**Comment by Tacombel** [comment]
Yea, this is in LKO

**Comment by Tacombel** [comment]
I just went to check it, press the button... and it worked. Whatever was happening is there no more.
