### ISSUE TITLE
Konstructor

### ISSUE THREAD

**Issue by Tacombel** [BobPalmer/Konstruction#87]
Missing some resources I added them with hyperedit with the construction UI open. Now, even as it recognizes that there are enough resources, the build button is greyed out.
Selecting another ship and then going back to the original unlocks it.

![image](https://user-images.githubusercontent.com/17971083/111806640-7c02cc80-88d2-11eb-838d-026988abbf8d.png)

**Comment by tjdeckard** [comment]
Fixed in linked PR
