### ISSUE TITLE
Spectacular Flip when activating magnet

### ISSUE THREAD

**Issue by bart-r-willems** [BobPalmer/Konstruction#9]
Not sure if this is a unity bug or a problem with the crane... or both. But when trying to pick up a not-so-heavy payload the entire crane flips over, even though it's mounted behind the fulcrum. It's almost like attaching the payload generates excessive torque that doesn't get properly absorbed by the wheels. 

No complaints, I'm grateful for the modding work that you do; I just think it's an interesting bug.

![craneflip](https://cloud.githubusercontent.com/assets/18702401/19256716/a38b168e-8f37-11e6-964f-9136fb42ff69.gif)

[Surface Base Construction Crane 2.zip](https://github.com/BobPalmer/Konstruction/files/520811/Surface.Base.Construction.Crane.2.zip)

**Comment by 5thHorseman** [comment]
I think you have an in-game implementation of this:
[Magnet Car](http://i.imgur.com/WxPl4.jpg)

Which doesn't work in the real world of course but hey, this is a video game. Is that whole thing one ship, or is the lander can and adapter a separate thing? Maybe there's clipping going on?

**Comment by bart-r-willems** [comment]
They're two separate craft. The crane vehicle is trying to lift the hitchhiker, which is not part of the crane vehicle. They're two craft. They're not connected. Not a magnet car.

What does seem to happen is that the hitchhiker is kind of catapulted towards the magnet and its momentum topples over the crane. It takes a ton of velocity though in those 10 cm that the can is pulled upwards. The magnet seems very finicky anyway, and appears to pull harder when the distance increases.

**Comment by MadMerlyn** [comment]
I've noticed this exact issue as well. I basically can't use the crane at all without stabilizers regardless of payload weight.

**Comment by dboi88** [comment]
Suggest close. Turning on magnets when at full strength always causes issues. This is noted on the wiki and in the KSPEDIA entry.

**Comment by BobPalmer** [comment]
Yep.  Don't turn on magnets at full strength ;)
